using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DD.CBU.Compute.Api.Contracts.Network20;

namespace DD.CBU.Compute.Api.Contracts.Image20
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	using System.Xml.Serialization;

	// 
	// This source code was auto-generated by xsd, Version=4.6.1055.0.
	// 


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
	public partial class historicalImageExports
	{

		private HistoricalImageExportType[] historicalImageExportField;

		private int pageNumberField;

		private bool pageNumberFieldSpecified;

		private int pageCountField;

		private bool pageCountFieldSpecified;

		private int totalCountField;

		private bool totalCountFieldSpecified;

		private int pageSizeField;

		private bool pageSizeFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("historicalImageExport")]
		public HistoricalImageExportType[] historicalImageExport
		{
			get
			{
				return this.historicalImageExportField;
			}
			set
			{
				this.historicalImageExportField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int pageNumber
		{
			get
			{
				return this.pageNumberField;
			}
			set
			{
				this.pageNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool pageNumberSpecified
		{
			get
			{
				return this.pageNumberFieldSpecified;
			}
			set
			{
				this.pageNumberFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int pageCount
		{
			get
			{
				return this.pageCountField;
			}
			set
			{
				this.pageCountField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool pageCountSpecified
		{
			get
			{
				return this.pageCountFieldSpecified;
			}
			set
			{
				this.pageCountFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int totalCount
		{
			get
			{
				return this.totalCountField;
			}
			set
			{
				this.totalCountField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool totalCountSpecified
		{
			get
			{
				return this.totalCountFieldSpecified;
			}
			set
			{
				this.totalCountFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int pageSize
		{
			get
			{
				return this.pageSizeField;
			}
			set
			{
				this.pageSizeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool pageSizeSpecified
		{
			get
			{
				return this.pageSizeFieldSpecified;
			}
			set
			{
				this.pageSizeFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
	public partial class HistoricalImageExportType
	{

		private string ovfPackagePrefixField;

		private string userNameField;

		private HistoricalImageExportTypeImageSummary imageSummaryField;

		private string responseCodeField;

		private object itemField;

		private string imageExportIdField;

		private System.DateTime startTimeField;

		private System.DateTime endTimeField;

		/// <remarks/>
		public string ovfPackagePrefix
		{
			get
			{
				return this.ovfPackagePrefixField;
			}
			set
			{
				this.ovfPackagePrefixField = value;
			}
		}

		/// <remarks/>
		public string userName
		{
			get
			{
				return this.userNameField;
			}
			set
			{
				this.userNameField = value;
			}
		}

		/// <remarks/>
		public HistoricalImageExportTypeImageSummary imageSummary
		{
			get
			{
				return this.imageSummaryField;
			}
			set
			{
				this.imageSummaryField = value;
			}
		}

		/// <remarks/>
		public string responseCode
		{
			get
			{
				return this.responseCodeField;
			}
			set
			{
				this.responseCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("failed", typeof(HistoricalImageExportTypeFailure))]
		[System.Xml.Serialization.XmlElementAttribute("succeeded", typeof(HistoricalImageExportTypeSuccess))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string imageExportId
		{
			get
			{
				return this.imageExportIdField;
			}
			set
			{
				this.imageExportIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime startTime
		{
			get
			{
				return this.startTimeField;
			}
			set
			{
				this.startTimeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime endTime
		{
			get
			{
				return this.endTimeField;
			}
			set
			{
				this.endTimeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
	public partial class HistoricalImageExportTypeImageSummary
	{

		private string nameField;

		private string descriptionField;

		private ClusterType clusterField;

		private GuestType guestField;

		private CpuType cpuField;

		private uint memoryGbField;

		private HistoricalImageExportTypeImageSummaryDisk[] diskField;

		private HistoricalImageExportTypeImageSummaryNic[] nicField;

		private string[] softwareLabelField;

		private string idField;

		private string datacenterIdField;

		/// <remarks/>
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public string description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public ClusterType cluster
		{
			get
			{
				return this.clusterField;
			}
			set
			{
				this.clusterField = value;
			}
		}

		/// <remarks/>
		public GuestType guest
		{
			get { return this.guestField; }
			set { this.guestField = value; }
		}

		/// <remarks/>
		public CpuType cpu
		{
			get
			{
				return this.cpuField;
			}
			set
			{
				this.cpuField = value;
			}
		}

		/// <remarks/>
		public uint memoryGb
		{
			get
			{
				return this.memoryGbField;
			}
			set
			{
				this.memoryGbField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("disk")]
		public HistoricalImageExportTypeImageSummaryDisk[] disk
		{
			get
			{
				return this.diskField;
			}
			set
			{
				this.diskField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("nic")]
		public HistoricalImageExportTypeImageSummaryNic[] nic
		{
			get
			{
				return this.nicField;
			}
			set
			{
				this.nicField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("softwareLabel")]
		public string[] softwareLabel
		{
			get
			{
				return this.softwareLabelField;
			}
			set
			{
				this.softwareLabelField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string datacenterId
		{
			get
			{
				return this.datacenterIdField;
			}
			set
			{
				this.datacenterIdField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
	public partial class ImageExportFileType
	{

		private string nameField;

		private string typeField;

		private long sizeBytesField;

		private System.DateTime lastModifiedTimeField;

		private System.DateTime expiryTimeField;

		/// <remarks/>
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public long sizeBytes
		{
			get
			{
				return this.sizeBytesField;
			}
			set
			{
				this.sizeBytesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime lastModifiedTime
		{
			get
			{
				return this.lastModifiedTimeField;
			}
			set
			{
				this.lastModifiedTimeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime expiryTime
		{
			get
			{
				return this.expiryTimeField;
			}
			set
			{
				this.expiryTimeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
	public partial class HistoricalImageExportTypeImageSummaryDisk
	{

		private int scsiIdField;

		private int sizeGbField;

		private string speedField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int scsiId
		{
			get
			{
				return this.scsiIdField;
			}
			set
			{
				this.scsiIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int sizeGb
		{
			get
			{
				return this.sizeGbField;
			}
			set
			{
				this.sizeGbField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string speed
		{
			get
			{
				return this.speedField;
			}
			set
			{
				this.speedField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
	public partial class HistoricalImageExportTypeImageSummaryNic
	{

		private string networkAdapterField;

		private int keyField;

		private bool keyFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string networkAdapter
		{
			get
			{
				return this.networkAdapterField;
			}
			set
			{
				this.networkAdapterField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool keySpecified
		{
			get
			{
				return this.keyFieldSpecified;
			}
			set
			{
				this.keyFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
	public partial class HistoricalImageExportTypeFailure
	{

		private string failureReasonField;

		/// <remarks/>
		public string failureReason
		{
			get
			{
				return this.failureReasonField;
			}
			set
			{
				this.failureReasonField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
	public partial class HistoricalImageExportTypeSuccess
	{

		private ImageExportFileType[] outputFileField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("outputFile")]
		public ImageExportFileType[] outputFile
		{
			get
			{
				return this.outputFileField;
			}
			set
			{
				this.outputFileField = value;
			}
		}
	}

}
